### ISSUE TITLE
Ability to remove a namespace

### ISSUE THREAD

**Issue by jawadst** [inboxapp/inbox#111]
Hi,

I've been playing around with the open-source version of Inbox and I was wondering if there was an option to remove a namespace (in both the open-source and the hosted versions). I had a quick look at the API doc and the code and I could not find anything.

Thanks for your great project btw!

Jawad

**Comment by emfree** [comment]
@filipposironi added a `bin/delete-account` script in https://github.com/inboxapp/inbox/commit/47fcc03 -- just sync past that commit and run `alembic upgrade head` to update the database schema in order to use it. Note that this will really truly delete the namespace and any data synced for it.

**Comment by jawadst** [comment]
Great, you guys are amazing! Any reason you didn't want to add it as an API call (DELETE /n/:id, for instance)?

**Comment by spang** [comment]
Thanks. :) This operation is very time-consuming, so an API call would have to use a queue and it's unclear how it should return or notify the client of successful or failed completion. This shouldn't be something anyone has to do often, though---is there a particular use case you see where having a DELETE API call would be useful?

**Comment by jawadst** [comment]
I get it. When users want to delete accounts then we need an API call :)
But we can definitely work around it by having our own queue that'd call the delete-account script.

Thanks,
Jawad

**Comment by spang** [comment]
Got it. Btw, you should totally drop a note by support@inboxapp.com letting us know what you're building. We love hearing from folks! :)
