### ISSUE TITLE
cannot acquire gevent lock

### ISSUE THREAD

**Issue by StefanIvanciuc** [inboxapp/inbox#116]
Hi guys,

First to be clear I don't consider this to be an real issue because I'ts properly working on one vm. The problem is that on the second I get this error and don't know how to fix it. So I though this is the best place to search for help.

On the vm I talked about when I run inbox-start it gets the following error:

```
[ERROR] {"account_id": 14, "level": "error", "timestamp": "2015-01-28T09:50:08.872014Z", "module": "inbox.mailsync.service:195", "cpu_id": 0, "greenlet_id": 139972075588816, "message": "cannot acquire gevent lock; associated file is /var/lock/inbox_sync/14.lock", "event": "sync_error"
```

and it gets it a lot.

Any help is welcomed. I can't figure out what is the root of this.

@grinich @emfree

**Comment by khamidou** [comment]
Hi Stefan,

This error tends to occur when there's two `inbox-sync` processes running at the same time. Is it the case? If not, try restarting the vm, removing the file and running `inbox-start` again.

**Comment by StefanIvanciuc** [comment]
Thanks Karim.

Seems that removing the lock files fixed this issue. 

By any change did you ever tried to use inbox alongside with supervisord?
When I:

```
cd inbox-path
bin/inbox-start
```

everything works fine. It sees new email right away.

But when I start it with supervisor:

```
user=inbox
directory=inbox-path
command=python bin/inbox-start
```

it almost never syncs new emails even it runs constantly. And I didn't noticed any strange errors besides some I've also noticed when running the normal way.

@khamidou

**Comment by khamidou** [comment]
We run inbox-start on production with supervisor but we don't have the issue you reported. Could you tell me what's the output of the program?
(Adding the following lines to your supervisor config file should do the job:)
```
stdout_logfile=/var/log/mailsync.log
stderr_logfile=/var/log/inbox/mailsync.err.log
```

**Comment by StefanIvanciuc** [comment]
Tested in a fresh vm and it has nothing to do with the supervisor. Maybe some other variables affect it.

**Comment by StefanIvanciuc** [comment]
Sure,

Out log: http://laravel.io/bin/Yy5d6
Err log: http://laravel.io/bin/Gyq3P

**Comment by khamidou** [comment]
Hmm, that's really weird. Could you open a new ticket to track it? Also, are you sure that this is only happening when running under supervisor?

**Comment by StefanIvanciuc** [comment]
Ok opened a separate issue. Thanks again Karim.
