### ISSUE TITLE
Support for non-SSL/TLS accounts

### ISSUE THREAD

**Issue by thomasst** [inboxapp/inbox#124]
There are still IMAP servers out there that have no support for secure connections. There should be a flag that allows syncing these accounts.

**Comment by grinich** [comment]
All the major providers support TLS.

We have decided not to support providers which cannot ensure a secure connection.

**Comment by thomasst** [comment]
We have some customers with non-SSL accounts we need to sync. Would you still be interested in merging a PR if I submit one?

**Comment by grinich** [comment]
@thomasst I'm hesitant to go down this road. I'd rather just keep the web secure.
